# Generated by Django 3.1.2 on 2021-01-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210102_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='num_b',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='feed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='num_e',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='num_m',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
